### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by r-barnes** [sahrk/DGGRID#24]
Adding
```
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-omit-frame-pointer -fsanitize=address")
set (CMAKE_LINKER_FLAGS "${CMAKE_LINKER_FLAGS} -fno-omit-frame-pointer -fsanitize=address")
```
to `CMakeLists.txt` in the `cmake` branch causes the code to compile with address sanitizing.

Running the code reveals a large number of memory leaks and other issues. I've tried to address some of these in #22 and #23, but I don't think I'll be able to fix everything. There are some deep design issues---such as classes holding arrays of pointers to themselves---which probably require some extensive refactoring to fix, and I simply don't have enough knowledge of the codebase.

The CRAN maintainers have taken dggridR, the R wrapper for DGGRID, down until the memory issues are fixed and are unwilling to negotiate on it :-/

**Comment by sahrk** [comment]
I saw your pull requests before this issue, or would have replied to this first. 

That is unfortunate about CRAN. I agree that making DGGRID meet their criteria will be quite an effort. DGGRID was designed to perform a single operation per execution: setup a grid, operate, and then exit. Creating a DGGS object instantiates a complex web of circular references that will exist until the program terminates. And I had seen on earlier complex high performance projects that memory management really impacts performance. So I made the decision to only worry about who owns what created object during the "operate" phase (so memory use doesn’t grow unbounded after setup). Performance is also the reason I’m wary of language solutions like unique_ptr that involve overhead, at least without some performance testing. It may be that there needs to be two versions of dglib (or one with a compiler switch).

I appreciate your efforts on all of this, but I guess ultimately it’ll need to be me that fixes or otherwise comes to terms with the memory leaks. 

I also appreciate your forbearance on the cmake pull request. I am working on a merge that includes conditional use of GDAL and wanted to slip that in first, since it impacts the build system. I got side-tracked trying to shoehorn in some other unrelated changes from that fork, but am freezing those for now. Once the conditional GDAL merge is in I’m hoping you can revise your cmake pull request to include the conditional build, and then I will finally get that merged.

**Comment by r-barnes** [comment]
I empathize: memory management on complex projects can be quite challenging!

I think the overhead of `unique_ptr` should be relatively low since most of the pointer's semantics can be enforced during compilation; however, this is not the case for `shared_ptr`, so it's overhead will be higher. One point to consider is how often the pointers get dereferenced. I haven't profiled DGGRID's performance, but if most of the time is spent, say, doing trigonometry than the additional overhead of smart pointers is unlikely to have much impact.

If you drop me a line when you have the conditional GDAL worked out, I can certainly integrate that into the cmake system.

**Comment by r-barnes** [comment]
I was just looking into `shared_ptr` today. I think most of their overhead can be avoided if they're passed by reference into functions (copies invoke atomic increment/decrement, so that's slow) or the raw pointer is retrieved and passed to functions which don't manage lifetime. As a way of associating pointers with objects that are created/destroyed infrequently but unpredictably the overhead should be relatively low.

**Comment by sahrk** [comment]
DGGRID version 7.2 now runs all examples under AddressSanitizer with no leaks or errors.

**Comment by sahrk** [comment]
Cleaning up old issues...
