### ISSUE TITLE
weird behavior on some Macs

### ISSUE THREAD

**Issue by jsocolar** [sahrk/DGGRID#62]
Some pretty spooky behavior is bubbling up in users of R package dggridR that I think must have its origins in DGGRID itself.  I think the most complete statement of the issue is [here](https://github.com/r-barnes/dggridR/issues/63#issuecomment-1454929653), though as noted [this](https://github.com/r-barnes/dggridR/issues/54) looks like the same issue.  The issue has only been reported by users of M1 chips, but it isn't clear what the significance of that is--maybe it's specific to the M1 architecture, or maybe it is specific to some other aspect of these machines (e.g. the C++ compiler or goodness knows what else).

**Comment by sahrk** [comment]
Thanks for the heads up @jsocolar, I think you're probably right that this is a DGGRID issue so I'm going to have to have a look at it. Alas, I hate hunting weird numeric bugs...

**Comment by jsocolar** [comment]
Thanks @sahrk! Happy to run tests on M1 for you if that's helpful, though I'd need relatively complete and explicit instructions for how to run them.  Love DGGRID!

**Comment by sahrk** [comment]
> Thanks @sahrk! Happy to run tests on M1 for you if that's helpful

Why I was just about to ask you if you might be willing to do so, thanks!

I'd like to confirm that the problem is with `DGGRID` and not `dggridR`. Could you build `DGGRID` from this repository, if you don't already have it? (See `INSTALL.md`)

Then put the two attached files `geoPts.txt` and `meta.txt` into your current directory and run:

`DGGRID/build/src/apps/dggrid/dggrid meta.txt &> output.txt`

Then please give me the resulting files `output.txt` and `seqNums.txt`.

Note that `geoPts.txt` contains the problem points from your issue, which are clustered near an icosahedron edge near a vertex (see picture). So I'm betting the ISEA projection is failing in some way.

![geoPts](https://user-images.githubusercontent.com/13046432/226514337-dae93f84-fda3-45cf-aa6c-3c8fbbc29cf5.png)
[geoPts.txt](https://github.com/sahrk/DGGRID/files/11024909/geoPts.txt)
[meta.txt](https://github.com/sahrk/DGGRID/files/11024914/meta.txt)

**Comment by jsocolar** [comment]
Sorry this took me so long!  I'm pretty sure I've managed to do the right steps.  In case it matters DGGRID did not find GDAL on my system.  The two files you requested are attached. 
[output.txt](https://github.com/sahrk/DGGRID/files/11184578/output.txt)
[seqNums.txt](https://github.com/sahrk/DGGRID/files/11184579/seqNums.txt)

**Comment by sahrk** [comment]
Thanks @jsocolar, that looks perfect and no worries on the time! I don't think the lack of GDAL should matter. I notice that the M1 has a 64 bit `long double`, vs. the 128 bits on intel Macs, which may somehow be causing the issues. Your `output.txt` narrowed down where the issue is manifesting; I'm wondering if I could ask you to do another run to narrow it down even more?

To do so, first update to (or download the latest version of) the master branch of DGGRID. Then in `DGGRID/src/lib/dglib/include/dglib/DgBase.h` line 36 change `#define DGDEBUG  0` to `#define DGDEBUG  1`. Then run `make`. 

Then put the two attached files into your current directory and run:
`DGGRID/build/src/apps/dggrid/dggrid transformMeta.txt &> output.txt`

Finally, please give me the resulting files `output.txt` and `transformed.txt`.

[input.txt](https://github.com/sahrk/DGGRID/files/11279995/input.txt)
[transformMeta.txt](https://github.com/sahrk/DGGRID/files/11279996/transformMeta.txt)
