### ISSUE TITLE
Holes formed by clipping

### ISSUE THREAD

**Issue by changliao1025** [sahrk/DGGRID#67]
Hi, 
I am adding support for the dggrid mesh inside the HexWatershed/pyflowline model. 
I found that there are some holes formed by the surrounding cells. This may break some of our code.
Is there any way to fill these holes?

P.S. The boundary/clip geojson file does not have holes. But the polygon is irregular.

![image](https://github.com/sahrk/DGGRID/assets/20618384/729bf108-6632-494e-af29-2f5b472515da)

**Comment by sahrk** [comment]
I'm not sure what is happening without more information. To start, could you display the clipping polygon over the generated hexagons so I can understand their relationship?

**Comment by changliao1025** [comment]
I overlay the polygon on the generated mesh:
<img width="1275" alt="image" src="https://github.com/sahrk/DGGRID/assets/20618384/30f6c649-a7b7-41f4-9a7f-4e182d739546">

**Comment by changliao1025** [comment]
I wonder whether it is possible to apply a convert hull algorithm (https://en.wikipedia.org/wiki/Convex_hull) in the end to include those missing cells in the final output. My understanding is that the clipping algorithm is using within or intersect to determine whether a cell should be kept or not.

**Comment by changliao1025** [comment]
I observed a similar pattern in our #pyflowline package for the MPAS mesh:
<img width="1272" alt="image" src="https://github.com/sahrk/DGGRID/assets/20618384/7dc78d10-114c-4bb6-b77a-e1fa6bbbdbcf">

**Comment by sahrk** [comment]
@changliao1025 thanks for the pictures, which confirm that the clipping algorithm is performing as intended: as you say it is including hexes that intersect (or are contained by) the clipping polygons. Unfortunately I'm not seeing how to fix this issue without introducing extra hexes, as I'm pretty sure would happen if you tried to use a convex hull (because it would also fill-in all the concave parts of the shoreline). But if some extra hexes aren't a problem for your project then I think the easiest fix might be to run a "buffer" operation on the polygons in a GIS before feeding them to DGGRID.

**Comment by changliao1025** [comment]
@sahrk After examining my own code in the clip part, I think this is a resolution mismatch issue. The code is indeed doing what is intended. The quick fix is to modify the polygon as you suggested. I also added an extra algorithm at the end (not the convex hull approach though) to add back small holes. This is only useful before the mesh generation is finished of course.
